[general]
    # If not set, logger will be set to info
    logger_level = "info"

# Database connection configuration
[database]
    postgres_host = "localhost"
    postgres_port = 5432
    postgres_user = 'user'
    postgres_password = 'password'
    postgres_db = 'database_name'