import { chainsConfig, getChainsConfigItem, logger, readConfig } from "./validationcore-database-scheme/common";
import { createConnection, createConnections } from "typeorm";
import * as config from "config";
import * as api from "./api";
import * as cache from "./cache";
import { test } from "./test";

/**
 * Responsible for API startup. Validates the config and exposes the API
 */
export function main(): void {
  // Text generated by https://patorjk.com/software/taag/#p=display&f=Slant&t=Validationcore%20Api
  console.log(
    " _    __      ___     __      __  _                                     ___          _ \n" +
      "| |  / /___ _/ (_)___/ /___ _/ /_(_)___  ____  _________  ________     /   |  ____  (_)\n" +
      "| | / / __ `/ / / __  / __ `/ __/ / __ \\/ __ \\/ ___/ __ \\/ ___/ _ \\   / /| | / __ \\/ / \n" +
      "| |/ / /_/ / / / /_/ / /_/ / /_/ / /_/ / / / / /__/ /_/ / /  /  __/  / ___ |/ /_/ / /  \n" +
      "|___/\\__,_/_/_/\\__,_/\\__,_/\\__/_/\\____/_/ /_/\\___/\\____/_/   \\___/  /_/  |_/ .___/_/   \n" +
      "                                                                          /_/          "
  );
  console.log("    by Blacklusion - 2021\n\n");

  logger.info("Starting up Validationcore api...");

  // Read Config and abort if config is not set correctly
  logger.info("Reading Config...");

  if (!readConfig()) {
    logger.fatal("Aborting Startup...");
    return;
  }

  // Create a separate connection for every chain
  const connections = [];
  for (const chainId in chainsConfig) {
    // todo: check await
    if (typeof chainId === "string") {
      connections.push({
        name: chainId,
        type: "postgres",
        host: config.get("database.postgres_host"),
        port: config.get("database.postgres_port"),
        username: config.get("database.postgres_user"),
        password: config.get("database.postgres_password"),
        database: getChainsConfigItem(chainId, "name"),
        entities: [__dirname + "/validationcore-database-scheme/entity/*{.js,.ts}"],
        synchronize: true,
      });
    }
  }
  createConnections(connections)
    .then(async (database) => {
      logger.info("Successfully connected to database");

      logger.info("++++++++  STARTUP COMPLETE  ++++++++");

      /**
       * START API (express server)
       */
      api.start();

      /**
       * START Cache
       */
      cache.start();
    })
    .catch((error) => {
      logger.error("Error while connecting to database ", error);
    });
}

main();
